### ISSUE TITLE
Cant turn off the empty window after using the script

### ISSUE THREAD

**Issue by dungnt95** [effektsvk/bodymovin-numbercount-aescript#1]
Hi, 
Im currently trying your script to create a number counter effect but I cant close the empty window and have to force quit AE, is there anyway to solve this problems.

**Comment by dungnt95** [comment]
I figure out, just press the esc on keyboard. Your script saves my day, thank you (Y)

**Comment by effektsvk** [comment]
Hey! Thanks for using the script, it means a lot. ❤️ I'm sorry I made it in one day and then didn't work on it anymore, maybe I'll get to it someday. 😉
